name = "Sidpatchy's Vanilla++"
author = "Sidpatchy"
version = "7.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbd5f72651305e318d6d1b3664cc6eb48c065471cede1b485538812fb72d531c"

[versions]
minecraft = "1.20.1"
quilt = "0.19.5"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
