name = "Sidpatchy's Vanilla++"
author = "Sidpatchy"
version = "8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e645c033abc46df87d0b1fedea24493a252560b252a909d5e968ee8103ef6d21"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21", "1.21.10", "1.21.11"]
