name = "Sidpatchy's Vanilla++"
author = "Sidpatchy"
version = "5.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4950abad5f9c9284dcf774939f3f223f68e28dc89a28b3c016b9b1fbf9f18f4"

[versions]
minecraft = "1.19.3"
quilt = "0.18.2"

[options]
acceptable-game-versions = ["1.19.3"]
