name = "Sidpatchy's Vanilla++"
author = "Sidpatchy"
version = "4.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d8f0b7dd11c768ee4dc6c850e6aeb98b7ae036c8b0bddcb39c9a1c936b918e6"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0"
