name = "Sidpatchy's Vanilla++"
author = "Sidpatchy"
version = "8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06d8d2549ff24963e14c681bc0b412b192f9849d85885f81d2bd32a6021d58aa"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21", "1.21.10", "1.21.11"]
