name = "Sidpatchy's Vanilla++"
author = "Sidpatchy"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf63abad1fe39e4f7fc85368cf5d0ce6732058bf97fbdaf910c65d1f37aef6c6"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
