name = "Effective 💦"
filename = "effective-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3580/78/effective-1.1.jar"
hash-format = "murmur2"
hash = "1768545296"

[update]
[update.curseforge]
file-id = 3580078
project-id = 556381
