name = "GameInfo"
filename = "GameInfo-mod-2.1.3a-1.18-build-Test 1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3582/985/GameInfo-mod-2.1.3a-1.18-build-Test 1.18.1.jar"
hash-format = "murmur2"
hash = "3083563485"

[update]
[update.curseforge]
file-id = 3582985
project-id = 366240
