name = "Mouse Wheelie (Fabric)"
filename = "mousewheelie-1.10.1+mc1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "061a0817be57d8de3fa03316ae745ed0fb22c7e7"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3847238
project-id = 317514
