name = "Screenshot to Clipboard (Fabric)"
filename = "screenshot-to-clipboard-1.0.9-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3643/25/screenshot-to-clipboard-1.0.9-fabric.jar"
hash-format = "murmur2"
hash = "3636455836"

[update]
[update.curseforge]
file-id = 3643025
project-id = 327154
