name = "Smooth Swapping (Fabric)"
filename = "Fabric-1.18-SmoothSwapping-0.4.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/382/Fabric-1.18-SmoothSwapping-0.4.4.jar"
hash-format = "murmur2"
hash = "917568238"

[update]
[update.curseforge]
file-id = 3590382
project-id = 513689
