name = "spark"
filename = "spark-1.8.6-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3644/349/spark-1.8.6-fabric.jar"
hash-format = "murmur2"
hash = "2450252204"

[update]
[update.curseforge]
file-id = 3644349
project-id = 361579
