name = "Visuality"
filename = "visuality-0.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3651/34/visuality-0.4.1.jar"
hash-format = "murmur2"
hash = "15812812"

[update]
[update.curseforge]
file-id = 3651034
project-id = 521126
