name = "Visuality"
filename = "visuality-0.4.0-1.18-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3585/609/visuality-0.4.0-1.18-fabric.jar"
hash-format = "murmur2"
hash = "1056300002"

[update]
[update.curseforge]
file-id = 3585609
project-id = 521126
